chore: make the tasks more CLI for the maru runner
Usage:
  maru COMMAND [flags]
  maru [command]

Available Commands:
  auth        [beta] Authentication commands for pulling private remote task files
  completion  Generate the autocompletion script for the specified shell
  help        Help about any command
  run         Runs a specified task from a task file
  version     Shows the version of the running runner binary

Flags:
  -h, --help               help for maru
  -l, --log-level string   Log level for the runner. Valid options are: error, warn, info, debug, trace (default "info")
      --no-log-file        Disable log file creation (default true)
      --no-progress        Disable fancy UI progress bars, spinners, logos, etc
      --tmpdir string      Specify the temporary directory to use for intermediate files

Use "maru [command] --help" for more information about a command. compatible

diff --git a/tasks/actions.yaml b/tasks/actions.yaml
--- a/tasks/actions.yaml
+++ b/tasks/actions.yaml
@@ -52,19 +52,19 @@ tasks:
       - description: Print basic debug info for a k8s cluster
         cmd: |
           echo "::group::kubectl get all"
-          uds zarf tools kubectl get all -A || echo "failed" | tee ${{ .variables.LOG_DIR }}/debug-k-get-all.log
+          ./zarf tools kubectl get all -A || echo "failed" | tee ${{ .variables.LOG_DIR }}/debug-k-get-all.log
           echo "::endgroup::"
           echo "::group::kubectl get pv,pvc"
-          uds zarf tools kubectl get pv,pvc -A || echo "failed" | tee ${{ .variables.LOG_DIR }}/debug-k-get-pv-pvc.log
+          ./zarf tools kubectl get pv,pvc -A || echo "failed" | tee ${{ .variables.LOG_DIR }}/debug-k-get-pv-pvc.log
           echo "::endgroup::"
           echo "::group::kubectl get package"
-          uds zarf tools kubectl get package -A || echo "failed" | tee ${{ .variables.LOG_DIR }}/debug-k-get-package.log
+          ./zarf tools kubectl get package -A || echo "failed" | tee ${{ .variables.LOG_DIR }}/debug-k-get-package.log
           echo "::endgroup::"
           echo "::group::kubectl get events"
-          uds zarf tools kubectl get events -A --sort-by='.lastTimestamp' || echo "failed" | tee ${{ .variables.LOG_DIR }}/debug-k-get-events.log
+          ./zarf tools kubectl get events -A --sort-by='.lastTimestamp' || echo "failed" | tee ${{ .variables.LOG_DIR }}/debug-k-get-events.log
           echo "::endgroup::"
           echo "::group::kubectl describe nodes"
-          uds zarf tools kubectl describe nodes k3d-uds-server-0 || echo "failed" | tee ${{ .variables.LOG_DIR }}/debug-k-describe-node.log
+          ./zarf tools kubectl describe nodes k3d-uds-server-0 || echo "failed" | tee ${{ .variables.LOG_DIR }}/debug-k-describe-node.log
           echo "::endgroup::"
 
   - name: clean-gh-runner
@@ -274,4 +274,4 @@ tasks:
       - description: Registry Login
         cmd: |
           set -x
-          echo "${{ .inputs.registry_token }}" | ./uds zarf tools registry login -u "${{ .inputs.registry_username }}" --password-stdin "${{ .inputs.registry }}"
+          echo "${{ .inputs.registry_token }}" | ././zarf tools registry login -u "${{ .inputs.registry_username }}" --password-stdin "${{ .inputs.registry }}"
