fix failure handling, re-organize script

diff --git a/tasks/badge.yaml b/tasks/badge.yaml
--- a/tasks/badge.yaml
+++ b/tasks/badge.yaml
@@ -2,31 +2,37 @@
 
 variables:
   - name: CHART_PATH
-    description: Relative path to the directory with the uds-config chart
+    description: "Relative path to the directory with the uds-config chart"
     default: chart/
   - name: GROUP_NAME
-    description: The name of the niche/group that the package fits into. E.g. package,swf,lfai
+    description: "The name of the niche/group that the package fits into. E.g. package,swf,lfai"
     default: package
   - name: COMMON_ZARF
-    description: Whether or not there is a common zarf.yaml file
+    description: "Whether or not there is a common zarf.yaml file"
     default: "true"
   - name: PACKAGE_DIR
-    description: Base directory where packages are located, relative to the root of the repository
+    description: "Base directory where packages are located, relative to the root of the repository"
     default: .
 
 tasks:
   - name: verify-badge
     actions:
-      - description: Verify that the package meets UDS badging standards
+      - description: "Verify that the package meets UDS badging standards"
         shell:
           linux: bash
           darwin: bash
         cmd: |
-          # Functions
+          ########
+          # COUNTS
+          ########
 
           WARNINGS=0
           ERRORS=0
-          CATASTROPHIC_ERRORS=0
+          FAILURES=0
+
+          ###########
+          # FUNCTIONS
+          ###########
 
           gh_notice() {
             if [[ "${CI}" == "true" ]]; then
@@ -51,11 +57,11 @@ tasks:
             echo "$1"
           }
 
-          gh_catastrophic_error() {
+          gh_failure() {
             if [[ "${CI}" == "true" ]]; then
-              printf "::error::"
+              printf "::failure::"
             fi
-            CATASTROPHIC_ERRORS=$((CATASTROPHIC_ERRORS + 1))
+            FAILURES=$((FAILURES + 1))
             echo "$1"
           }
 
@@ -75,7 +81,11 @@ tasks:
             fi
           }
 
-          gh_group "📃 Setup"
+          ################
+          # INITIALIZATION
+          ################
+
+          gh_group "📃 Setup Package Variables"
 
           # Default values for vars, maru-runner issue workaround
           CHART_PATH=${CHART_PATH:-chart/}
@@ -97,6 +107,14 @@ tasks:
             gh_error "  ❌ kubectl-validate failed to install"
           fi
 
+          gh_endgroup
+
+          ########################
+          # STATIC CODE VALIDATION
+          ########################
+
+          gh_group "🔍 Package Structure Validation"
+
           if [[ "${COMMON_ZARF}" == "true" ]]; then
             NAMESPACE=$(uds zarf tools yq '.components[].charts[].namespace' "${PACKAGE_DIR}/common/zarf.yaml" | uniq)
           else
@@ -105,42 +123,132 @@ tasks:
           fi
           gh_notice "  ℹ️  Namespace: $NAMESPACE"
 
+          # Should expose all configuration (uds.dev CRs, additional Secrets/ConfigMaps, etc) through a Helm chart (ideally in a chart or charts directory).
+          if [ "${COMMON_ZARF}" == "true" ]; then
+            COMMON_ZARF_MANIFEST_COUNT=$(uds zarf tools yq '.components[] | select(.manifests != null)' "${PACKAGE_DIR}/common/zarf.yaml" | wc -l)
+            if [ "$COMMON_ZARF_MANIFEST_COUNT" -gt 0 ]; then
+              gh_error "  ❌ Manifests present in common/zarf.yaml"
+            else
+              gh_notice "  ✅ No manifests present in common/zarf.yaml"
+            fi
+          fi
+
+          MAIN_ZARF_MANIFEST_COUNT=$(uds zarf tools yq '.components[] | select(.manifests != null)' "${PACKAGE_DIR}/zarf.yaml" | wc -l)
+          if [ "$MAIN_ZARF_MANIFEST_COUNT" -gt 0 ]; then
+            gh_error "  ❌ Manifests present in zarf.yaml"
+          else
+            gh_notice "  ✅ No manifests present in zarf.yaml"
+          fi
+
+          # Should implement or allow for multiple flavors (ideally with common definitions in a common directory)
+          ZARF_COMPONENTS_FLAVOR_COUNT=$(uds zarf tools yq '.components[] | select(.only.flavor != null)' "${PACKAGE_DIR}/zarf.yaml" | wc -l)
+          if [ "$ZARF_COMPONENTS_FLAVOR_COUNT" -eq 0 ]; then
+            gh_error "  ❌ No flavors defined in zarf.yaml"
+          else
+            gh_notice "  ✅ At least one flavor defined in zarf.yaml"
+          fi
+
+          gh_endgroup
+
+          gh_group "🔍 Package Testing Validation"
+
+          # Must implement Journey Testing to cover the basic user flows and features of the application, especially where an application interacts with an external service/interface.
+          if [ -d "${PACKAGE_DIR}/tests" ]; then
+            if [ "$(ls -A "${PACKAGE_DIR}/tests")" ]; then
+              gh_notice "  ✅ Tests folder exists and has files"
+            else
+              gh_error "  ❌ Tests folder exists but is empty"
+            fi
+          else
+            # Tests might be at the root of a mono-repository
+            if [ -d "tests" ]; then
+              if [ "$(ls -A "tests")" ]; then
+                gh_notice "  ✅ Tests folder exists and has files"
+              else
+                gh_error "  ❌ Tests folder exists but is empty"
+              fi
+            else
+              gh_error "  ❌ Tests folder does not exist"
+            fi
+          fi
+
+          gh_endgroup
+
+          gh_group "🔍 Versioning Validation"
+
+          # Must be consistently versioned across flavors - this can take many forms but flavors should differ in image bases/builds not application versions.
+
+          ZARF_PKG_VERSION=$(uds zarf tools yq '.metadata.version' "${PACKAGE_DIR}/zarf.yaml" | cut -d '-' -f1)
+          IMAGE_WITH_ZARF_VERSION_COUNT=$(uds zarf tools yq '.components[].images[]' "${PACKAGE_DIR}/zarf.yaml" | grep -o "${ZARF_PKG_VERSION}" | wc -l)
+
+          if [ "$IMAGE_WITH_ZARF_VERSION_COUNT" -ge "$ZARF_COMPONENTS_FLAVOR_COUNT" ]; then
+            gh_notice "  ✅ Version is consistent across flavors and package"
+          else
+            gh_warning "  ⚠️ Version is not consistent across flavors and package"
+          fi
+
+          gh_endgroup
+
+          #############################
+          # DYNAMIC PACKAGE VALIDATIONS
+          #############################
+
+          gh_group "🔍 Exemptions Validation"
+
+          # Must minimize the scope and number of the exemptions to only what is absolutely required by the application
+          EXEMPTION_COUNT=$(kubectl get Exemptions -n "${NAMESPACE}" -o json | jq -r '.items | length')
+          if [ "$EXEMPTION_COUNT" -gt 0 ]; then
+            gh_warning "  ⚠️  Exemptions are present, review needed"
+          else
+            gh_notice "  ✅ No exemptions present"
+          fi
+
+          gh_endgroup
+
+          UDS_PACKAGE_CR_EXISTS="false"
+
+          gh_group "📃 Get the UDS Package CR"
+
           # Extract UDS_PACKAGE_NAME from zarf.yaml
           UDS_PACKAGE_NAME=$(uds zarf tools yq '.metadata.name' "${PACKAGE_DIR}/zarf.yaml")
           gh_notice "  ℹ️  Package Name: $UDS_PACKAGE_NAME"
 
-          # Retrieve the specific Package resource
-          gh_notice "  ℹ️  Retrieving UDS Package JSON for $UDS_PACKAGE_NAME..."
-          if UDS_PACKAGE_JSON=$(kubectl get Package "$UDS_PACKAGE_NAME" -n "${NAMESPACE}" -o json); then
-            gh_notice "  ℹ️  Retrieved UDS Package JSON for $UDS_PACKAGE_NAME"
-            PACKAGE_FOUND=true
+          # The following may fail if the UDS Package CR does not exist
+          set +e
+
+          # Try to retrieve the specific Package resource
+          UDS_PACKAGE_JSON=$(kubectl get Package "$UDS_PACKAGE_NAME" -n "${NAMESPACE}" -o json 2>/dev/null)
+
+          # Check if the kubectl command succeeded
+          if [ $? -eq 0 ]; then
+              UDS_PACKAGE_CR_EXISTS="true"
+              gh_notice "  ℹ️  Retrieved UDS Package JSON for $UDS_PACKAGE_NAME"
           else
-            gh_catastrophic_error "  ❌ Failed to retrieve Package $UDS_PACKAGE_NAME in namespace $NAMESPACE"
-            PACKAGE_FOUND=false
+              gh_failure "  ⛔  UDS Package CR does not exist for $UDS_PACKAGE_NAME"
           fi
+
+          set -e
 
           gh_endgroup
 
-          gh_group "🔍 Config Chart Validation"
+          if [ "$UDS_PACKAGE_CR_EXISTS" == "true" ]; then
+            gh_group "🔍 UDS Config Chart Validation"
 
-          # Validate UDS Package/Config chart is valid
+            # Validate UDS Package/Config chart is valid
+            gh_notice "  ℹ️  Validating uds-config chart..."
+            printf "\033[A"
+            if ${GOBIN}/kubectl-validate <(helm template "${PACKAGE_DIR}/${CHART_PATH}" | grep -v '^ *#' | perl -p0e 's/---[\s---]*---/---/sg') &>/tmp/validate-output; then
+              gh_notice "  ✅ uds-config chart is valid"
+            else
+              gh_error "  ❌ uds-config chart is invalid"
+              cat /tmp/validate-output | sed 's/^/    /'
+            fi
 
-          gh_notice "  ℹ️  Validating uds-config chart..."
-          printf "\033[A"
-          if ${GOBIN}/kubectl-validate <(helm template "${PACKAGE_DIR}/${CHART_PATH}" | grep -v '^ *#' | perl -p0e 's/---[\s---]*---/---/sg') &> /tmp/validate-output; then
-            gh_notice "  ✅ uds-config chart is valid"
-          else
-            gh_error "  ❌ uds-config chart is invalid"
-            cat /tmp/validate-output | sed 's/^/    /'
-          fi
+            gh_endgroup
 
-          gh_endgroup
+            gh_group "🔍 Istio Validation"
 
-          gh_group "🔍 Istio Validation"
-
-          if [ "$PACKAGE_FOUND" = true ]; then
-            ## Must define any external interfaces under the expose key.
-
+            # Must define any external interfaces under the expose key.
             ENDPOINTS="$(echo "$UDS_PACKAGE_JSON" | jq -r '.status.endpoints[]')"
             gh_notice "  ℹ️  Endpoints: $ENDPOINTS"
 
@@ -156,8 +264,7 @@ tasks:
 
             echo
 
-            ## Must deploy and operate successfully with Istio injection enabled in the namespace.
-
+            # Must deploy and operate successfully with Istio injection enabled in the namespace.
             POD_COUNT=$(kubectl get pods -n "${NAMESPACE}" --no-headers | wc -l)
             POD_SIDECAR_COUNT=$(kubectl get pods -n "${NAMESPACE}" -o json | jq '.items[] | select(.spec.containers[].name == "istio-proxy")' | wc -l)
 
@@ -169,8 +276,7 @@ tasks:
 
             echo
 
-            ## Should avoid workarounds such as disabling strict mTLS peer authentication.
-
+            # Should avoid workarounds such as disabling strict mTLS peer authentication.
             PEERAUTH=$(kubectl get Peerauthentication -n "${NAMESPACE}" -o=json | jq -r '.items[].spec.mtls.mode')
 
             if [ "$PEERAUTH" != "STRICT" ] && [ "$PEERAUTH" != "" ]; then
@@ -178,17 +284,10 @@ tasks:
             else
               gh_notice "  ✅ Peerauthentication is set to strict"
             fi
-          else
-            gh_warning "  ⚠️  Skipping Istio Validation because Package CR not found"
-          fi
 
-          gh_endgroup
+            echo
 
-          gh_group "🔍 Network Policies Validation"
-
-          if [ "$PACKAGE_FOUND" = true ]; then
-            ## Must define network policies under the allow key as required.
-
+            # Must define network policies under the allow key as required.
             NETPOL_AMOUNT=$(echo "$UDS_PACKAGE_JSON" | jq -r '.spec.network.allow | length')
 
             if [ "$NETPOL_AMOUNT" -eq 0 ]; then
@@ -197,8 +296,7 @@ tasks:
               gh_notice "  ✅ Network policies are defined"
             fi
 
-            ## Should minimize network policies to specific selectors needed for Ingress/Egress traffic.
-
+            # Should minimize network policies to specific selectors needed for Ingress/Egress traffic.
             NETPOL_EXT_COUNT=$(echo "$UDS_PACKAGE_JSON" | jq -r '.spec.network.allow[] | select(.remoteGenerated != "IntraNamespace")' | jq -s 'length')
             gh_notice "  ℹ️  Non-IntraNamespace network policies: $NETPOL_EXT_COUNT"
 
@@ -229,18 +327,14 @@ tasks:
             else
               gh_notice "  ✅ No network policies with 'remoteGenerated: Anywhere' are present"
             fi
-          else
-            gh_warning "  ⚠️  Skipping Network Policies Validation because Package CR not found"
-          fi
 
-          gh_endgroup
+            gh_endgroup
 
-          gh_group "🔍 Keycloak/SSO Validation"
+            gh_group "🔍 Keycloak/SSO Validation"
 
-          if [ "$PACKAGE_FOUND" = true ]; then
             SSO_CLIENT_COUNT=$(echo "$UDS_PACKAGE_JSON" | jq -r '.spec.sso | length')
 
-            ## Must use and create a Keycloak client through the sso key if the application provides a user login.
+            # Must use and create a Keycloak client through the sso key if the application provides a user login.
             if [ "$SSO_CLIENT_COUNT" -gt 0 ]; then
               gh_notice "  ℹ️  There are $SSO_CLIENT_COUNT SSO clients defined"
 
@@ -283,17 +377,12 @@ tasks:
             else
               gh_warning "  ⚠️  No SSO configuration found, review needed"
             fi
-          else
-            gh_warning "  ⚠️  Skipping Keycloak/SSO Validation because Package CR not found"
-          fi
 
-          gh_endgroup
+            gh_endgroup
 
-          gh_group "🔍 Monitoring Validation"
+            gh_group "🔍 Monitoring Validation"
 
-          ## Must implement monitors for each application metrics endpoint using its built-in chart monitors, the Package CR monitor key, or manual monitors in the config chart.
-
-          if [ "$PACKAGE_FOUND" = true ]; then
+            # Must implement monitors for each application metrics endpoint using its built-in chart monitors, the Package CR monitor key, or manual monitors in the config chart.
             PKG_MONITOR_COUNT=$(echo "$UDS_PACKAGE_JSON" | jq -r '.spec.monitor | length')
 
             if [ "$PKG_MONITOR_COUNT" -eq 0 ]; then
@@ -320,99 +409,20 @@ tasks:
               gh_notice "  ✅ Monitor defined in UDS Package"
               gh_warning "  ⚠️  There may be more monitors to implement, review needed"
             fi
-          else
-            gh_warning "  ⚠️  Skipping Monitoring Validation because Package CR not found"
+
+            gh_endgroup
           fi
-
-          gh_endgroup
-
-          gh_group "🔍 Exemptions Validation"
-
-          ## Must minimize the scope and number of the exemptions to only what is absolutely required by the application
-
-          EXEMPTION_COUNT=$(kubectl get Exemptions -n "${NAMESPACE}" -o json | jq -r '.items | length')
-          if [ "$EXEMPTION_COUNT" -gt 0 ]; then
-            gh_warning "  ⚠️  Exemptions are present, review needed"
-          else
-            gh_notice "  ✅ No exemptions present"
-          fi
-
-          gh_endgroup
-
-          gh_group "🔍 Package Structure Validation"
-
-          ## Should expose all configuration (uds.dev CRs, additional Secrets/ConfigMaps, etc) through a Helm chart (ideally in a chart or charts directory).
-
-          if [ "${COMMON_ZARF}" == "true" ]; then
-            COMMON_ZARF_MANIFEST_COUNT=$(uds zarf tools yq '.components[] | select(.manifests != null)' "${PACKAGE_DIR}/common/zarf.yaml" | wc -l)
-            if [ "$COMMON_ZARF_MANIFEST_COUNT" -gt 0 ]; then
-              gh_error "  ❌ Manifests present in common/zarf.yaml"
-            else
-              gh_notice "  ✅ No manifests present in common/zarf.yaml"
-            fi
-          fi
-
-          MAIN_ZARF_MANIFEST_COUNT=$(uds zarf tools yq '.components[] | select(.manifests != null)' "${PACKAGE_DIR}/zarf.yaml" | wc -l)
-          if [ "$MAIN_ZARF_MANIFEST_COUNT" -gt 0 ]; then
-            gh_error "  ❌ Manifests present in zarf.yaml"
-          else
-            gh_notice "  ✅ No manifests present in zarf.yaml"
-          fi
-
-          ## Should implement or allow for multiple flavors (ideally with common definitions in a common directory)
-
-          ZARF_COMPONENTS_FLAVOR_COUNT=$(uds zarf tools yq '.components[] | select(.only.flavor != null)' "${PACKAGE_DIR}/zarf.yaml" | wc -l)
-          if [ "$ZARF_COMPONENTS_FLAVOR_COUNT" -eq 0 ]; then
-            gh_error "  ❌ No flavors defined in zarf.yaml"
-          else
-            gh_notice "  ✅ At least one flavor defined in zarf.yaml"
-          fi
-
-          gh_endgroup
-
-          gh_group "🔍 Package Testing Validation"
-
-          ## Must implement Journey Testing to cover the basic user flows and features of the application, especially where an application interacts with an external service/interface.
-
-          if [ -d "${PACKAGE_DIR}/tests" ]; then
-            if [ "$(ls -A "${PACKAGE_DIR}/tests")" ]; then
-              gh_notice "  ✅ Tests folder exists and has files"
-            else
-              gh_error "  ❌ Tests folder exists but is empty"
-            fi
-          else
-            gh_error "  ❌ Tests folder does not exist"
-          fi
-
-          gh_endgroup
-
-          gh_group "🔍 Versioning Validation"
-
-          # Must be consistently versioned across flavors - this can take many forms but flavors should differ in image bases/builds not application versions.
-
-          ZARF_PKG_VERSION=$(uds zarf tools yq '.metadata.version' "${PACKAGE_DIR}/zarf.yaml" | cut -d '-' -f1)
-          IMAGE_WITH_ZARF_VERSION_COUNT=$(uds zarf tools yq '.components[].images[]' "${PACKAGE_DIR}/zarf.yaml" | grep -o "${ZARF_PKG_VERSION}" | wc -l)
-
-          if [ "$IMAGE_WITH_ZARF_VERSION_COUNT" -ge "$ZARF_COMPONENTS_FLAVOR_COUNT" ]; then
-            gh_notice "  ✅ Version is consistent across flavors and package"
-          else
-            gh_warning "  ⚠️ Version is not consistent across flavors and package"
-          fi
-
-          gh_endgroup
-
           # Summary
 
-          if [ "$CATASTROPHIC_ERRORS" -gt 0 ]; then
-            gh_error "❌ $CATASTROPHIC_ERRORS catastrophic error(s) found"
+          if [ "$FAILURES" -gt 0 ]; then
+            gh_error "⛔ $FAILURES failures found"
           fi
           if [ "$ERRORS" -gt 0 ]; then
-            gh_error "❌ $ERRORS error(s) found"
+            gh_error "❌ $ERRORS errors found"
           fi
           if [ "$WARNINGS" -gt 0 ]; then
-            gh_warning "⚠️  $WARNINGS warning(s) found"
+            gh_warning "⚠️  $WARNINGS warnings found"
           fi
-          if [ "$CATASTROPHIC_ERRORS" -eq 0 ] && [ "$ERRORS" -eq 0 ] && [ "$WARNINGS" -eq 0 ]; then
-            gh_notice "✅ No errors or warnings found"
+          if [ "$FAILURES" -eq 0 ] && [ "$ERRORS" -eq 0 ] && [ "$WARNINGS" -eq 0 ]; then
+            gh_notice "✅ No failures, errors nor warnings found"
           fi
-
