feat: adds a callable workflow for republishing a package (#449)

diff --git a/tasks/create.yaml b/tasks/create.yaml
--- a/tasks/create.yaml
+++ b/tasks/create.yaml
@@ -29,7 +29,81 @@ tasks:
             ./uds zarf package create ${{ .inputs.path }} --confirm --no-progress --architecture="${{ .inputs.architecture }}" --flavor "${FLAVOR}" ${{ .inputs.options }}
           else
             echo "Registry1 packages cannot be made for 'arm64'"
+            exit 1
           fi
+
+  - name: recreate-latest-tag-package
+    description: Recreate the UDS Zarf Package in the repository
+    inputs:
+      options:
+        description: For setting create time variables and flags
+      path:
+        description: Path to the zarf package definition being created
+        default: .
+      architecture:
+        description: The architecture of the package to create
+        default: ${UDS_ARCH}
+      config:
+        description: Optionally provide a path to a Zarf config file
+        default: ""
+        required: false
+      flavor:
+        description: The flavor of the package to publish
+        default: ${FLAVOR}
+    actions:
+      - description: Remove copied repo
+        cmd: rm -rf recreate-test
+
+      - description: Copy repo into the recreate-test folder
+        shell:
+          linux: bash
+          darwin: bash
+        cmd: |
+          mkdir recreate-test
+
+          shopt -s extglob dotglob
+          cp -r !(recreate-test) recreate-test
+          shopt -u dotglob
+
+      - env:
+          - ZARF_CONFIG=${{ .inputs.config }}
+        shell:
+          linux: bash
+          darwin: bash
+        dir: recreate-test
+        cmd: |
+          git reset --hard HEAD
+
+          # Get the latest tag matching the FLAVOR pattern
+          REPUBLISH_TAG=$(git tag --list "*-${{ .inputs.flavor }}" --sort=-v:refname | head -n 1)
+
+          # Checkout the tag if it exists
+          if [[ -n "$REPUBLISH_TAG" ]]; then
+              git checkout "$REPUBLISH_TAG"
+          else
+              echo "No tag found for flavor '${{ .inputs.flavor }}'. Skipping."
+              exit 1
+          fi
+
+          uds-pk release update-yaml ${{ .inputs.flavor }}
+
+          if [ "${FLAVOR}" != "registry1" ] || [ "${{ .inputs.architecture }}" != "arm64" ]; then
+            ./uds zarf package create ${{ .inputs.path }} --confirm --no-progress --architecture="${{ .inputs.architecture }}" --flavor "${FLAVOR}" ${{ .inputs.options }}
+          else
+            echo "Registry1 packages cannot be made for 'arm64'"
+            exit 1
+          fi
+
+          PACKAGE_NAME=$(cat ${{ .inputs.path }}/zarf.yaml | ./uds zarf tools yq .metadata.name)
+          LOCAL_VERSION=$(cat ${{ .inputs.path }}/zarf.yaml | ./uds zarf tools yq .metadata.version)
+
+          mv "${{ .inputs.path }}/zarf-package-${PACKAGE_NAME}-${{ .inputs.architecture }}-${LOCAL_VERSION}.tar.zst" "../${{ .inputs.path }}/zarf-package-${PACKAGE_NAME}-${{ .inputs.architecture }}-${LOCAL_VERSION}.tar.zst"
+
+      - description: Remove the recreate-test folder
+        cmd: rm -rf recreate-test
+
+      - description: Reversion the bundle.yaml to match the latest tag
+        cmd: uds-pk release update-yaml ${{ .inputs.flavor }}
 
   - name: test-bundle
     description: Create the test bundle (bundling package + dependencies for testing)
