fix: always run verify test and fail if not successful (#592)

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -52,6 +52,15 @@ jobs:
   verify-test:
     runs-on: ubuntu-latest
     needs: validate
+    if: always()
     steps:
-      - name: Success
-        run: echo "All tests passed successfully!"
+      - name: Check validate result
+        run: |
+          echo "validate result: ${{ needs.validate.result }}"
+
+          if [ "${{ needs.validate.result }}" != "success" ]; then
+            echo "One or more tests failed."
+            exit 1
+          fi
+
+          echo "All tests passed successfully!"
